### ISSUE TITLE
Longitudinal vs multi-day 'sessions'

### ISSUE THREAD

**Issue by alexlicohen** [BIDS-Apps/freesurfer#11]
Presently, the code assumes that the longitudinal pipeline should be run if multiple sessions are present, however it is sometimes the case (often in clinical research) that the two sessions are only a few days apart. What should be the most appropriate way to handle this?

- a switch to reset longitudinal_study back to False?
or something else?

**Comment by chrisgorgo** [comment]
I think added the command line switch that would treat a T1w from multiple sessions as if they were all acquired on one session is the best option here.

**Comment by alexlicohen** [comment]
Which should be the default:
combine all data into one session, or
treat sessions with T1 data as independent sessions

**Comment by chrisgorgo** [comment]
It seems that treating sessions with T1 data as independent sessions is a more reasonable default.
