### ISSUE TITLE
FSL required for: Pial Refinement, diffusion functions, and TRACULA

### ISSUE THREAD

**Issue by alexlicohen** [BIDS-Apps/freesurfer#13]

**Comment by chrisgorgo** [comment]
FYI - TRACULA is getting a dedicated BIDS App https://github.com/BIDS-Apps/tracula

**Comment by alexlicohen** [comment]
True, but pial refinement calls fslregister. 

-Alex

**Comment by chrisgorgo** [comment]
Of course - we still need FSL. I'm just letting you know since I thought it would be relevant.

**Comment by alexlicohen** [comment]
Ah gotcha, I thought perhaps you knew a work around...

-Alex

**Comment by chrisgorgo** [comment]
Closed by #14
