### ISSUE TITLE
Group tables

### ISSUE THREAD

**Issue by fliem** [BIDS-Apps/freesurfer#19]
How about renaming group -> group1, and adding group-level stats tables (aparcstats2table, asegstats2table) as group2? I could work on that.

**Comment by chrisgorgo** [comment]
Sounds useful. Is the idea that you could run `group2` without running `group1`?

**Comment by fliem** [comment]
Yes.

**Comment by alexlicohen** [comment]
Would it make sense to have: group, that does the full process, and groupstats, that just does the statistics? That way it maintains the BIDS participant/group split but allows for rerunning the stats. 

-Alex

**Comment by fliem** [comment]
I don't have a strong opinion here. AFAI remember, the 2tables commands take a couple of seconds for  largish datasets, so it wouldn't considerably add to the template process.

**Comment by fliem** [comment]
I've implemented this in #26. 
Since template-creation and table export are two independent use cases, table export now only is run in `group2`.

**Comment by fliem** [comment]
Closed by #26
