### ISSUE TITLE
T2 and T2 failure modes with multiple input

### ISSUE THREAD

**Issue by alexlicohen** [BIDS-Apps/freesurfer#20]
if there are multiple T2 or FLAIR images in the directory structure, the T2pial or FLAIRpial stages do not seem to be run.

Additionally, if multiple T1s are provided, but of different resolution, freesurfer crashes.

I'm thinking to write an additional switch to select the BIDS -rec_xyz- tags to designate a particular image to use and/or users can generate their own averages and assign them a -rec_avg- tag

i.e., labeling files as sub-003_ses-01_acq-mprage_rec-forFS_run-01_T1w.nii.gz
or
sub-003_ses-01_acq-mprage_rec-avg_T1w.nii.gz

**Comment by chrisgorgo** [comment]
On Wed, Jan 25, 2017 at 8:22 AM, Alexander Li Cohen <
notifications@github.com> wrote:

> if there are multiple T2 or FLAIR images in the directory structure, the
> T2pial or FLAIRpial stages do not seem to be run.
>
That's not good - what's the traceback?

> Additionally, if multiple T1s are provided, but of different resolution,
> freesurfer crashes.
>
This is expected freesurfer behaviour. Last time I checked on the mailing
list using multiple T1s coming from different acqusitions is not
recommended.

> I'm thinking to write an additional switch to select the BIDS -rec_xyz-
> tags to designate a particular image to use and/or users can generate their
> own averages and assign them a -rec_avg- tag
>
> i.e., labeling files as sub-003_ses-01_acq-mprage**_re
> c-forFS**_run-01_T1w.nii.gz
> or
> sub-003_ses-01_acq-mprage**_rec-avg**_T1w.nii.gz
>
We already have  --acquisition_label ACQUISITION_LABEL that can be used to
do that. Why would users want to make their own averages?

**Comment by alexlicohen** [comment]
For the multiple T2s, I believe it might just be the -T2pial flag being repeated, in testing now... for the T1s, sometimes the acq is the same, but the field of view was different... this could be handled off line with anew acq code though...

-Alex

**Comment by chrisgorgo** [comment]
On Wed, Jan 25, 2017 at 9:07 AM, Alexander Li Cohen <
notifications@github.com> wrote:

> For the multiple T2s, I believe it might just be the -T2pial flag being
> repeated, in testing now... for the T1s, sometimes the acq is the same, but
> the field of view was different... this could be handled off line with anew
> acq code though...
>
Yes if the field of view is different it should be a new acq label.


>
> -Alex
>
> > On Jan 25, 2017, at 11:28 AM, Chris Filo Gorgolewski <

**Comment by alexlicohen** [comment]
The T2 pial failure I was encountering is not related to the BIDS-App code, it's within freesurfer itself (the -pial stage, specifically mris_make_surfaces was failing with my test case... still figuring out why...) so this issue can be closed, I will, however, make a pull request to add in an acquisition label switch for the T2/FLAIR sequence too (since that may be helpful to others).

**Comment by chrisgorgo** [comment]
Thank you!
