### ISSUE TITLE
force recomputation

### ISSUE THREAD

**Issue by fliem** [BIDS-Apps/freesurfer#25]
- At the moment we check if there is a is a `{fsid}/scripts/IsRunning.lh+rh` file. If it is there we remove the folder and start from scratch. 
- Elseif we check if there is a `{fid}` folder. If that's the case, we run the `resume_cmd`. If the recon-all has been completed, that seems to recompute everything. 

How about adding an input argument that needs to be set to recompute everything (like `--force-recompute`)? That way
- completed subjects that have been submitted to the analysis by mistake won't be computed
- we could probably run test cases for longitudinal data on circleci by providing the cross-sectional recons and only testing the base and long step (#23)

**Comment by alexlicohen** [comment]
Chris and I had discussed this when I added the `resume_cmd` for Issue #7, the reason for the current checks is to allow for resuming stages after manual correction, but still allowing for the novice, "run it again to rewrite everything" behavior.

This would change the default behavior to skipping subjects if the subject directory exists unless force-recompute is present, but if you want to run e.g., autorecon3, you would also have to set force-recompute, which may be confusing, but could be explained.

Chris, what do you think?

An alternative could be a `--longitudinal2` switch which goes straight to base and long (maybe using the `dontrun` stages flag).

On further reviewing the code, I believe the `stages `options is missing from the first round `run.py lines 158 and 162`, which also needs to be fixed.

**Comment by fliem** [comment]
> On further reviewing the code, I believe the stagesoptions is missing from the first round run.py lines 158 and 162, which also needs to be fixed.

That's probably on purpose. If only parts of `recon-all -all` is run at the cross-sectional phase, it think it is not possible to create a base image.

**Comment by alexlicohen** [comment]
well, the default is all, but what if you need to correct the
cross-sectional segmentation? I suppose in that case you are just running
the single participant, but I think with the current control logic, that's
the command that would be run...


----------------------------------------------------------------
Alexander Li Cohen, M.D., Ph.D.
E-mail: Alexander.Cohen2@childrens.harvard.edu (Medical/Science Email)
E-mail: alexcohen@gmail.com (Lifetime Email)
----------------------------------------------------------------

**Comment by PeerHerholz** [comment]
Ahoi hoi @fliem and @alexlicohen,

was there any further discussion re this? 
Otherwise, we could close this issue.

Cheers, Peer

**Comment by alexlicohen** [comment]
I think we can go ahead and close the issue.

-Alex

**Comment by PeerHerholz** [comment]
Ok, thx @alexlicohen!
