### ISSUE TITLE
Step decomposition in longitunal studies

### ISSUE THREAD

**Issue by ntraut** [BIDS-Apps/freesurfer#29]
Hello,
In longitudinal studies we do not have the possibility do decompose the execution in steps, sessions and stages. This may cause the execution to take a very long time and this can be a problem if we are running under a cluster with jobs limited to 24 hours.
It would be very nice if you let me to make a pull request to allow this decomposition...

**Comment by chrisgorgo** [comment]
Such pull request would be very much appreciated!

**Comment by fliem** [comment]
Thanks for merging. This issue can be closed now, correct?
Could you please make a new release. Thanks.
