### ISSUE TITLE
Bypass bids_validator

### ISSUE THREAD

**Issue by egarza** [BIDS-Apps/freesurfer#34]
Even in participant level, the bids_validator does not allow to run freesurfer if there are errors even in 'func' files such as '(code: 13 - SLICE_TIMING_NOT_DEFINED)'.

Any way to bypass this for the participant level?

**Comment by chrisgorgo** [comment]
`SLICE_TIMING_NOT_DEFINED` is a warning and should not stop freesurfer to run. Could you provide the full validator log?

**Comment by egarza** [comment]
Sorry for the delay.

Here is the full report. The T1w images are fine, it is some fMRI that have one more slice that are the problem really. But it shouldn't be for freesurfer.

Thanks!

Ed


```
egarza@Tezcatlipoca:/media/egarza/INP_MRI_Backup/projects/INP/addimex_tms/data/mri$ sudo docker run -i --rm -v /media/egarza/INP_MRI_Backup/projects/INP/addimex_tms/data/mri/bids:/bids_dataset:ro -v /media/egarza/INP_MRI_Backup/projects/INP/addimex_tms/data/mri/outputs_freesurfer:/outputs bids/freesurfer /bids_dataset /outputs participant --participant_label 001 --license_key "*CvJ/FFLEnSE." --multiple_sessions longitudinal --parcellations aparc.a2009s
[sudo] password for egarza: 
	1: You have to define 'TaskName' for this file. (code: 50 - TASK_NAME_MUST_DEFINE)
		/sub-001/ses-t0/func/sub-001_ses-t0_task-rest_bold.nii.gz
		/sub-001/ses-t1/func/sub-001_ses-t1_task-rest_bold.nii.gz
		/sub-002/ses-t0/func/sub-002_ses-t0_task-rest_bold.nii.gz
		/sub-002/ses-t1/func/sub-002_ses-t1_task-rest_bold.nii.gz
		/sub-003/ses-t0/func/sub-003_ses-t0_task-rest_bold.nii.gz
		/sub-003/ses-t1/func/sub-003_ses-t1_task-rest_bold.nii.gz
		/sub-004/ses-t0/func/sub-004_ses-t0_task-rest_bold.nii.gz
		/sub-004/ses-t1/func/sub-004_ses-t1_task-rest_bold.nii.gz
		/sub-005/ses-t0/func/sub-005_ses-t0_task-rest_bold.nii.gz
		/sub-006/ses-t0/func/sub-006_ses-t0_task-rest_bold.nii.gz
		... and 7 more files having this issue (Use --verbose to see them all).

	2: Bold scans must be 4 dimensional. (code: 54 - BOLD_NOT_4D)
		/sub-007/ses-t0/func/sub-007_ses-t0_task-rest_bold.nii.gz
			Evidence: header field "dim" = 3,80,80,11099

	1: This file is not part of the BIDS specification, make sure it isn't included in the dataset by accident. Data derivatives (processed data) should be placed in /derivatives folder. (code: 1 - NOT_INCLUDED)
		/dcm2bids_tms.sh
			Evidence: dcm2bids_tms.sh
		/sub-001/ses-t0/dki/sub-001_ses-t0_dki.bval
			Evidence: sub-001_ses-t0_dki.bval
		/sub-001/ses-t0/dki/sub-001_ses-t0_dki.bvec
			Evidence: sub-001_ses-t0_dki.bvec
		/sub-001/ses-t0/dki/sub-001_ses-t0_dki.json
			Evidence: sub-001_ses-t0_dki.json
		/sub-001/ses-t0/dki/sub-001_ses-t0_dki.nii.gz
			Evidence: sub-001_ses-t0_dki.nii.gz
		/sub-001/ses-t1/dki/sub-001_ses-t1_dki.bval
			Evidence: sub-001_ses-t1_dki.bval
		/sub-001/ses-t1/dki/sub-001_ses-t1_dki.bvec
			Evidence: sub-001_ses-t1_dki.bvec
		/sub-001/ses-t1/dki/sub-001_ses-t1_dki.json
			Evidence: sub-001_ses-t1_dki.json
		/sub-001/ses-t1/dki/sub-001_ses-t1_dki.nii.gz
			Evidence: sub-001_ses-t1_dki.nii.gz
		/sub-002/ses-t0/dki/sub-002_ses-t0_dki.bval
			Evidence: sub-002_ses-t0_dki.bval
		... and 289 more files having this issue (Use --verbose to see them all).

	2: You should define 'SliceTiming' for this file. If you don't provide this information slice time correction will not be possible. (code: 13 - SLICE_TIMING_NOT_DEFINED)
		/sub-001/ses-t0/func/sub-001_ses-t0_task-rest_bold.nii.gz
		/sub-001/ses-t1/func/sub-001_ses-t1_task-rest_bold.nii.gz
		/sub-002/ses-t0/func/sub-002_ses-t0_task-rest_bold.nii.gz
		/sub-002/ses-t1/func/sub-002_ses-t1_task-rest_bold.nii.gz
		/sub-003/ses-t0/func/sub-003_ses-t0_task-rest_bold.nii.gz
		/sub-003/ses-t1/func/sub-003_ses-t1_task-rest_bold.nii.gz
		/sub-004/ses-t0/func/sub-004_ses-t0_task-rest_bold.nii.gz
		/sub-004/ses-t1/func/sub-004_ses-t1_task-rest_bold.nii.gz
		/sub-005/ses-t0/func/sub-005_ses-t0_task-rest_bold.nii.gz
		/sub-006/ses-t0/func/sub-006_ses-t0_task-rest_bold.nii.gz
		... and 7 more files having this issue (Use --verbose to see them all).

	3: Not all subjects contain the same files. Each subject should contain the same number of files with the same naming unless some files are known to be missing. (code: 38 - INCONSISTENT_SUBJECTS)
		/sub-001/ses-t14/anat/sub-001_ses-t14_T1w.json
		/sub-001/ses-t14/anat/sub-001_ses-t14_T1w.nii.gz
		/sub-001/ses-t14/dwi/sub-001_ses-t14_dwi.bval
		/sub-001/ses-t14/dwi/sub-001_ses-t14_dwi.bvec
		/sub-001/ses-t14/dwi/sub-001_ses-t14_dwi.json
		/sub-001/ses-t14/dwi/sub-001_ses-t14_dwi.nii.gz
		/sub-001/ses-t14/func/sub-001_ses-t14_task-rest_bold.json
		/sub-001/ses-t14/func/sub-001_ses-t14_task-rest_bold.nii.gz
		/sub-002/ses-t14/anat/sub-002_ses-t14_T1w.json
		/sub-002/ses-t14/anat/sub-002_ses-t14_T1w.nii.gz
		... and 70 more files having this issue (Use --verbose to see them all).

	4: Not all subjects/sessions/runs have the same scanning parameters. (code: 39 - INCONSISTENT_PARAMETERS)
		/sub-001/ses-t0/dwi/sub-001_ses-t0_dwi.nii.gz
		/sub-002/ses-t0/dwi/sub-002_ses-t0_dwi.nii.gz
		/sub-003/ses-t0/dwi/sub-003_ses-t0_dwi.nii.gz
		/sub-004/ses-t0/dwi/sub-004_ses-t0_dwi.nii.gz
		/sub-005/ses-t0/func/sub-005_ses-t0_task-rest_bold.nii.gz
		/sub-006/ses-t0/func/sub-006_ses-t0_task-rest_bold.nii.gz
		/sub-006/ses-t1/dwi/sub-006_ses-t1_dwi.nii.gz
		/sub-007/ses-t0/func/sub-007_ses-t0_task-rest_bold.nii.gz
		/sub-007/ses-t1/dwi/sub-007_ses-t1_dwi.nii.gz
		/sub-008/ses-t0/func/sub-008_ses-t0_task-rest_bold.nii.gz
		... and 2 more files having this issue (Use --verbose to see them all).

        Summary:                 Available Tasks:        Available Modalities: 
        439 Files, 2.01GB                                T1w                   
        9 - Subjects                                     dwi                   
        3 - Sessions                                     bold                  


Traceback (most recent call last):
  File "/run.py", line 89, in <module>
    run("bids-validator " + args.bids_dir)
  File "/run.py", line 25, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 1
```

**Comment by chrisgorgo** [comment]
Right now the validation cannot be skipped. However, only the first two
messages are errors and are necessary to get fixed. This definitely will
not be time wasted and I'm sure it will pay off in the future.

On Aug 4, 2017 7:45 AM, "Eduardo Garza-Villarreal" <notifications@github.com>
wrote:

Sorry for the delay.

Here is the full report. The T1w images are fine, it is some fMRI that have
one more slice that are the problem really. But it shouldn't be for
freesurfer.

Thanks!

Ed

egarza@Tezcatlipoca:/media/egarza/INP_MRI_Backup/projects/INP/addimex_tms/data/mri$
sudo docker run -i --rm -v
/media/egarza/INP_MRI_Backup/projects/INP/addimex_tms/data/mri/bids:/bids_dataset:ro
-v /media/egarza/INP_MRI_Backup/projects/INP/addimex_tms/data/mri/outputs_freesurfer:/outputs
bids/freesurfer /bids_dataset /outputs participant --participant_label
001 --license_key "*CvJ/FFLEnSE." --multiple_sessions longitudinal
--parcellations aparc.a2009s
[sudo] password for egarza:
	1: You have to define 'TaskName' for this file. (code: 50 -
TASK_NAME_MUST_DEFINE)
		/sub-001/ses-t0/func/sub-001_ses-t0_task-rest_bold.nii.gz
		/sub-001/ses-t1/func/sub-001_ses-t1_task-rest_bold.nii.gz
		/sub-002/ses-t0/func/sub-002_ses-t0_task-rest_bold.nii.gz
		/sub-002/ses-t1/func/sub-002_ses-t1_task-rest_bold.nii.gz
		/sub-003/ses-t0/func/sub-003_ses-t0_task-rest_bold.nii.gz
		/sub-003/ses-t1/func/sub-003_ses-t1_task-rest_bold.nii.gz
		/sub-004/ses-t0/func/sub-004_ses-t0_task-rest_bold.nii.gz
		/sub-004/ses-t1/func/sub-004_ses-t1_task-rest_bold.nii.gz
		/sub-005/ses-t0/func/sub-005_ses-t0_task-rest_bold.nii.gz
		/sub-006/ses-t0/func/sub-006_ses-t0_task-rest_bold.nii.gz
		... and 7 more files having this issue (Use --verbose to see them all).

	2: Bold scans must be 4 dimensional. (code: 54 - BOLD_NOT_4D)
		/sub-007/ses-t0/func/sub-007_ses-t0_task-rest_bold.nii.gz
			Evidence: header field "dim" = 3,80,80,11099

	1: This file is not part of the BIDS specification, make sure it
isn't included in the dataset by accident. Data derivatives (processed
data) should be placed in /derivatives folder. (code: 1 -
NOT_INCLUDED)
		/dcm2bids_tms.sh
			Evidence: dcm2bids_tms.sh
		/sub-001/ses-t0/dki/sub-001_ses-t0_dki.bval
			Evidence: sub-001_ses-t0_dki.bval
		/sub-001/ses-t0/dki/sub-001_ses-t0_dki.bvec
			Evidence: sub-001_ses-t0_dki.bvec
		/sub-001/ses-t0/dki/sub-001_ses-t0_dki.json
			Evidence: sub-001_ses-t0_dki.json
		/sub-001/ses-t0/dki/sub-001_ses-t0_dki.nii.gz
			Evidence: sub-001_ses-t0_dki.nii.gz
		/sub-001/ses-t1/dki/sub-001_ses-t1_dki.bval
			Evidence: sub-001_ses-t1_dki.bval
		/sub-001/ses-t1/dki/sub-001_ses-t1_dki.bvec
			Evidence: sub-001_ses-t1_dki.bvec
		/sub-001/ses-t1/dki/sub-001_ses-t1_dki.json
			Evidence: sub-001_ses-t1_dki.json
		/sub-001/ses-t1/dki/sub-001_ses-t1_dki.nii.gz
			Evidence: sub-001_ses-t1_dki.nii.gz
		/sub-002/ses-t0/dki/sub-002_ses-t0_dki.bval
			Evidence: sub-002_ses-t0_dki.bval
		... and 289 more files having this issue (Use --verbose to see them all).

	2: You should define 'SliceTiming' for this file. If you don't
provide this information slice time correction will not be possible.
(code: 13 - SLICE_TIMING_NOT_DEFINED)
		/sub-001/ses-t0/func/sub-001_ses-t0_task-rest_bold.nii.gz
		/sub-001/ses-t1/func/sub-001_ses-t1_task-rest_bold.nii.gz
		/sub-002/ses-t0/func/sub-002_ses-t0_task-rest_bold.nii.gz
		/sub-002/ses-t1/func/sub-002_ses-t1_task-rest_bold.nii.gz
		/sub-003/ses-t0/func/sub-003_ses-t0_task-rest_bold.nii.gz
		/sub-003/ses-t1/func/sub-003_ses-t1_task-rest_bold.nii.gz
		/sub-004/ses-t0/func/sub-004_ses-t0_task-rest_bold.nii.gz
		/sub-004/ses-t1/func/sub-004_ses-t1_task-rest_bold.nii.gz
		/sub-005/ses-t0/func/sub-005_ses-t0_task-rest_bold.nii.gz
		/sub-006/ses-t0/func/sub-006_ses-t0_task-rest_bold.nii.gz
		... and 7 more files having this issue (Use --verbose to see them all).

	3: Not all subjects contain the same files. Each subject should
contain the same number of files with the same naming unless some
files are known to be missing. (code: 38 - INCONSISTENT_SUBJECTS)
		/sub-001/ses-t14/anat/sub-001_ses-t14_T1w.json
		/sub-001/ses-t14/anat/sub-001_ses-t14_T1w.nii.gz
		/sub-001/ses-t14/dwi/sub-001_ses-t14_dwi.bval
		/sub-001/ses-t14/dwi/sub-001_ses-t14_dwi.bvec
		/sub-001/ses-t14/dwi/sub-001_ses-t14_dwi.json
		/sub-001/ses-t14/dwi/sub-001_ses-t14_dwi.nii.gz
		/sub-001/ses-t14/func/sub-001_ses-t14_task-rest_bold.json
		/sub-001/ses-t14/func/sub-001_ses-t14_task-rest_bold.nii.gz
		/sub-002/ses-t14/anat/sub-002_ses-t14_T1w.json
		/sub-002/ses-t14/anat/sub-002_ses-t14_T1w.nii.gz
		... and 70 more files having this issue (Use --verbose to see them all).

	4: Not all subjects/sessions/runs have the same scanning parameters.
(code: 39 - INCONSISTENT_PARAMETERS)
		/sub-001/ses-t0/dwi/sub-001_ses-t0_dwi.nii.gz
		/sub-002/ses-t0/dwi/sub-002_ses-t0_dwi.nii.gz
		/sub-003/ses-t0/dwi/sub-003_ses-t0_dwi.nii.gz
		/sub-004/ses-t0/dwi/sub-004_ses-t0_dwi.nii.gz
		/sub-005/ses-t0/func/sub-005_ses-t0_task-rest_bold.nii.gz
		/sub-006/ses-t0/func/sub-006_ses-t0_task-rest_bold.nii.gz
		/sub-006/ses-t1/dwi/sub-006_ses-t1_dwi.nii.gz
		/sub-007/ses-t0/func/sub-007_ses-t0_task-rest_bold.nii.gz
		/sub-007/ses-t1/dwi/sub-007_ses-t1_dwi.nii.gz
		/sub-008/ses-t0/func/sub-008_ses-t0_task-rest_bold.nii.gz
		... and 2 more files having this issue (Use --verbose to see them all).

        Summary:                 Available Tasks:        Available Modalities:
        439 Files, 2.01GB                                T1w
        9 - Subjects                                     dwi
        3 - Sessions                                     bold


Traceback (most recent call last):
  File "/run.py", line 89, in <module>
    run("bids-validator " + args.bids_dir)
  File "/run.py", line 25, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 1

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/BIDS-Apps/freesurfer/issues/34#issuecomment-320267958>,
or mute the thread

**Comment by egarza** [comment]
Alright, so `code: 50 - TASK_NAME_MUST_DEFINE` and `code: 54 - BOLD_NOT_4Ds` should fix it?

Thanks

**Comment by chrisgorgo** [comment]
Yes.

**Comment by egarza** [comment]
That fixed it.

Thanks

**Comment by rsfmt** [comment]
Error 1: [Code 50] TASK_NAME_MUST_DEFINE
I am getting this error whenever i am validating my file how can i fix this ? thanks
