### ISSUE TITLE
License not being recognized...

### ISSUE THREAD

**Issue by jlhanson5** [BIDS-Apps/freesurfer#39]
I was trying to test drive the BIDS freesurfer app, but couldn't get my license to be recognized. 

My license exists as a file and is the new version (I'm using it for fmriprep... so I know it works/is valid).
`jamielh@pfc:~/Volumes/Hanson/NKI_HealthyBrainNetwork/SI/R1/derivatives$ ls /home/jamielh/Volumes/Hanson/NKI_HealthyBrainNetwork/SI/R1/derivatives/license.txt
/home/jamielh/Volumes/Hanson/NKI_HealthyBrainNetwork/SI/R1/derivatives/license.txt`

But this syntax:
`docker run -ti --rm -v /home/jamielh/Volumes/Hanson/NKI_HealthyBrainNetwork/SI/R1:/bids_dataset:ro -v /home/jamielh/Volumes/Hanson/NKI_HealthyBrainNetwork/SI/R1/derivatives/freesurfer:/outputs bids/freesurfer /bids_dataset /outputs participant --participant_label NDARAA075AMK --n_cpus 2 --stages autorecon1  --steps cross-sectional --skip_bids_validator --license_file "/home/jamielh/Volumes/Hanson/NKI_HealthyBrainNetwork/SI/R1/derivatives/license.txt"
`

Leads to this error output:
`Traceback (most recent call last):
  File "/run.py", line 167, in <module>
    raise Exception("Provided license file does not exist")
Exception: Provided license file does not exist`

What am I doing wrong with that command line call? I tried with and without quotation marks, etc., but no luck. Thoughts?

**Comment by chrisgorgo** [comment]
You need to mount the license file with `-v`

`docker run -ti --rm -v /home/jamielh/Volumes/Hanson/NKI_HealthyBrainNetwork/SI/R1:/bids_dataset:ro -v /home/jamielh/Volumes/Hanson/NKI_HealthyBrainNetwork/SI/R1/derivatives/freesurfer:/outputs -v /home/jamielh/Volumes/Hanson/NKI_HealthyBrainNetwork/SI/R1/derivatives/license.txt:/license.txt:ro bids/freesurfer /bids_dataset /outputs participant --participant_label NDARAA075AMK --n_cpus 2 --stages autorecon1 --steps cross-sectional --skip_bids_validator --license_file "/license.txt"`
