### ISSUE TITLE
No T1w nii files found for subject 01. Skipping subject.

### ISSUE THREAD

**Issue by tragus1** [BIDS-Apps/freesurfer#43]
Hi, 

I get this message "No T1w nii files found for subject 01. Skipping subject.", but there are T1w present in a validated BIDS dataset. What could be the reason?

Thanks,
Tragus

**Comment by PeerHerholz** [comment]
Ahoi hoi @tragus1,

was your problem ever solved?

Cheers, Peer

**Comment by noxtoby** [comment]
FWIW, I've seen this error when `--participant_label sub-01` should be `--participant_label 01`

The original error message above suggests that this might not be the case here

**Comment by Remi-Gau** [comment]
closing but reopen if this is still a problem
