### ISSUE TITLE
Error 1: [Code 50] TASK_NAME_MUST_DEFINE

### ISSUE THREAD

**Issue by rsfmt** [BIDS-Apps/freesurfer#46]
i am getting this error everytime i tried to validate my data how can i fix this ?

**Comment by PeerHerholz** [comment]
Ahoi hoi @rsfmt,

could you maybe provide more information, i.e. how does your dataset looks like and how do you run the app?

**Comment by Remi-Gau** [comment]
Closing as this seems to be a very old issue with no follow up.
