### ISSUE TITLE
Option to allow lower resolution T2s

### ISSUE THREAD

**Issue by Shotgunosine** [BIDS-Apps/freesurfer#51]
Currently T2s and FLAIRs with any single voxel dimension greater than 1.2 mm are not used. Could we add an option to allow a user to bypass that limit? I've got some 1x1x2mm T2s that I'd like to try to use to refine the surfaces before I have to resort to hand editing the surfaces.

**Comment by PeerHerholz** [comment]
Tackled and solved by @Shotgunosine in #60. Thus, the issue can be closed.
