### ISSUE TITLE
Use Neurodocker

### ISSUE THREAD

**Issue by Shotgunosine** [BIDS-Apps/freesurfer#54]
@PeerHerholz Do you think you've got time to try getting this working with neurodocker?

**Comment by PeerHerholz** [comment]
Sure thing, at it.

**Comment by PeerHerholz** [comment]
A first draft is up in #55, where I requested your review. Local build worked fine on my end. Could you maybe try it also on your machine?

**Comment by Shotgunosine** [comment]
Resolved by #55
