### ISSUE TITLE
Freesurfer 7 version?

### ISSUE THREAD

**Issue by eduardklap** [BIDS-Apps/freesurfer#57]
Hi, thanks for making this bids tool!
I was wondering whether you were planning to implement the new FreeSurfer 7.1 (https://surfer.nmr.mgh.harvard.edu/fswiki/rel7downloads) in the BIDS-app? Would be great!
If I could be of any help, let me know. Could be something for the OHBM Hackathon next week, which I will be attending :)

Best, 
Eduard

**Comment by PeerHerholz** [comment]
Ahoi hoi @eduardklap,

sorry for the late reply. I think it should definitely be supported, but a complete switch from version `6` to `7` should happen at some later point in time. However, this brings up a very interesting topic: should we support/allow multiple versions simultaneously? I think at least `6` and `7` should be supported for continuity reasons. I guess we could work with version specific tags as it's already done on [dockerhub](https://hub.docker.com/r/bids/freesurfer/tags). 
We could definitely start working on and testing version `7` in a dedicated branch.

**Comment by eduardklap** [comment]
Hi @PeerHerholz. Yes, would be great to have version 7 alongside version 6.
I am happy to help out with testing stuff. Have experience with running but not building docker containers, but willing to learn something new :)

**Comment by PeerHerholz** [comment]
Hi @eduardklap,

cool, thanks for your interest in helping out! No worries re containers, we'll go on this exiting journey together.
How about you fork the repo (if you haven't done it already), create a new branch and we go from there?

Cheers and thx again, Peer

**Comment by Shotgunosine** [comment]
I guess the ideal solution for this would involve a new release of neurodocker, but in the mean time, I've got a dockerfile that seems to make a freesurfer 7 version of the bids app here:
https://github.com/Shotgunosine/freesurfer/blob/fs_7/Dockerfile_fs7

**Comment by AndysWorth** [comment]
I'm hoping to see an official BIDS App version of Freesurfer 7.  What can I do to help?

Is this effort waiting for a new bug-fix release from the LCN/Martinos Center?  I know there are at least two issues with the [7.1.1 release](https://surfer.nmr.mgh.harvard.edu/fswiki/ReleaseNotes) where there are fixes but I see no timeline for a 7.1.2 release.  @Shotgunosine, a couple small changes to your fork/branch would fix those issues.  Should I work on a PR on your branch or should that be merged into the BIDS-Apps repo first?

**Comment by Shotgunosine** [comment]
@AndysWorth, I'd be happy to accept a PR to my branch. @PeerHerholz what do you think about going ahead with my solution?

**Comment by PeerHerholz** [comment]
@Shotgunosine Yeah, I think the parallel is the way to go. For the foreseeable future we should support both `6` and `7`.  Having dedicated branches for each version should also allow parallel automated builds and tests. If @AndysWorth pushes the required fixes to your branch we could merge things at the higher level. WDYT?

**Comment by Shotgunosine** [comment]
sounds good to me

**Comment by AndysWorth** [comment]
Great!

**Comment by AndysWorth** [comment]
I did a pull request just to update to the newer version of Freesurfer on the f_7 branch of Shotgunosine / freesurfer.  I had plans on getting the fix for the -parallel bug in (I think they have a new recon-all script), but I don't know where to find it.  If recon-all is called again after detecting a crash, it will finish properly.

**Comment by Shotgunosine** [comment]
@AndysWorth Might be worth an email to the freesurfer mailing list to see if you can track down the new recon-all script (or better yet, a URL for it). I'm not 100% sure how we'd get it into the images we build on circle, but I bet we could figure something out.

**Comment by AndysWorth** [comment]
I just emailed the list.

**Comment by noxtoby** [comment]
See also [here](https://github.com/bids-apps/freesurfer/issues/69#issuecomment-1236282494)

**Comment by Remi-Gau** [comment]
closed in #67
