### ISSUE TITLE
Introduce automated image builds

### ISSUE THREAD

**Issue by PeerHerholz** [BIDS-Apps/freesurfer#59]
While we're have tests running, we could/should also include automated builds through the dockerhub-github integration that follows specific build rules for e.g. `latest` vs. `specific` versions. WDYT @Shotgunosine?

**Comment by Shotgunosine** [comment]
Yeah, I think that'd be great, but I haven't set those up before, so I
don't know how much I'd be able to help.

**Comment by PeerHerholz** [comment]
KK, I'll check it out and keep you posted here.
@chrisgorgo sorry for stressing again, but do you know who owns the account for the [bids organization on dockerhub](https://hub.docker.com/u/bids)?

**Comment by Shotgunosine** [comment]
@effigies Do you know who owns the bids organization on dockerhub?

**Comment by Shotgunosine** [comment]
@PeerHerholz The circleci config should be pushing to github, do you see any error messages in any of the circleci jobs that get triggered after merging?

**Comment by effigies** [comment]
I suspect it's Chris, but IDK for sure. @yarikoptic and @tyarkoni might also know?

**Comment by tyarkoni** [comment]
All I know is it isn't me... I would also guess @chrisgorgo.

**Comment by PeerHerholz** [comment]
@Shotgunosine just checked and didn't see any error messages.

**Comment by Shotgunosine** [comment]
@PeerHerholz oh, you may have to tag a release to trigger it. You can created an annotated tag with `git tag -a v1.4 -m "my version 1.4"` with whatever version we want to call this release (I guess 6.0.1-6 if we want to follow Chris's pattern) and `git push --tags` to push it up to the repo.

**Comment by PeerHerholz** [comment]
Ah I see, sorry for not checking more closely. Do you want to do a release based on the current status or wait for some more additions, e.g. automated builds?

**Comment by Shotgunosine** [comment]
I think a release based on where we are now would be good.

**Comment by Shotgunosine** [comment]
I don't know much about the github integrations, but I do think we could also achieve side by side builds of v6.0.1 and v 7.0.1 with circleci if we wanted to go that route.

**Comment by PeerHerholz** [comment]
Yeah, I thought the same. I haven't done a lot with `v 7.0.1` yet and thus don't know if we would need to have parallel `docs` and `examples` as well?

**Comment by Shotgunosine** [comment]
I'm not sure. We could always stand one up and see if people start finding broken things.

**Comment by Remi-Gau** [comment]
I believe this has been taken care of.
