### ISSUE TITLE
Updating to current version of freesurfer

### ISSUE THREAD

**Issue by butellyn** [BIDS-Apps/freesurfer#69]
Hi! Is this app being maintained? If so, would it be possible to update it to the current version of freesurfer (7.2.0)?

**Comment by PeerHerholz** [comment]
Hi @butellyn,

thank you very much for opening this issue. 

We actually started the process of supporting `FreeSurfer 7` in #67 but didn't finish it. I guess it's time to do so now, wdyt @Shotgunosine?

Cheers, Peer

**Comment by noxtoby** [comment]
[This fork](https://github.com/e-dads/freesurfer) over at the [E-DADS](https://github.com/e-dads) github works for 7.1.1. Should be straightforward to replace [line 79 of Dockerfile_fs7](https://github.com/E-DADS/freesurfer/blob/b2fec9ac7b46366cc17382435e3f8df1e11462b9/Dockerfile_fs7#L79) with your desired version.

And if you're happy with 7.1.1, see [here](https://e-dads.github.io/tools/) for using the prebuilt docker at [noxtoby/edads:freesurfer7p1p1](https://hub.docker.com/r/noxtoby/edads/tags) and how to use docker2singularity for HPC cluster usage.

**Comment by PeerHerholz** [comment]
Thx so much for the pointer @noxtoby, that's definitely helpful.

**Comment by Remi-Gau** [comment]
completed in #67
