### ISSUE TITLE
rmtree removal

### ISSUE THREAD

**Issue by alexlicohen** [BIDS-Apps/freesurfer#7]
Currently, this does not allow for sequentially running autorecon1 then 2, etc... because of the deletion of the output directory if it exists:

if os.path.exists(os.path.join(output_dir, fsid)):
     rmtree(os.path.join(output_dir, fsid))
run(cmd)

The default should be to use the existing output directory per standard freesurfer convention. You could add an optional flag/option of --clean to switch the rmtree lines back on...

**Comment by chrisgorgo** [comment]
The tree removal is there to allow for restarting interrupted FreeSurfer runs. I wonder if there could be a smart way to distinguish between interrupted run and run that was instructed to go only through a subset of stages.

**Comment by alexlicohen** [comment]
To restart interrupted FreeSurfer runs, you just have to delete a file in
the scripts directory called "IsRunning".

There's also the situation of another freesurfer process activitely
processing in that output... if we don't need to account for that then this
would work:
If dir is present AND IsRunning is present -> rmtree then run cmd
If dir is present AND IsRunning is absent  -> run cmd (freesurfer knows
what to do)


otherwise, you could consider the following:
If dir is present AND IsRunning is present AND --force_overwrite is not set
-> error/exit (b/c it might be ok, just in use)
If dir is present AND IsRunning is present AND --force_overwrite is set ->
rmtree then run cmd (b/c you know it's been interrupted)
If dir is present AND IsRunning is absent AND --force_overwrite is not set
-> run cmd (freesurfer knows what to do for sequential processing)
If dir is present AND IsRunning is absent AND --force_overwrite is set
-> rmtree then run cmd (b/c you know it's been interrupted)


there is also "recon-all -make all -s <subject id>" which will attempt to
resume the interrupted process, but that may be too much...

https://surfer.nmr.mgh.harvard.edu/fswiki/UserContributions/FAQ#Q.Ihada.5BPowerOutage.7CComputerFailure.7CSpilledcoffeeoncomputer.7Cetc.5D.2ChowcanIresumetherecon-all.3F

-Alex


----------------------------------------------------------------
Alexander Li Cohen, M.D., Ph.D.
E-mail: Alexander.Cohen2@childrens.harvard.edu (Medical/Science Email)
E-mail: alexcohen@gmail.com (Lifetime Email)
----------------------------------------------------------------

**Comment by chrisgorgo** [comment]
I don't think we need to account for the situation where another process is
running. Looking for the IsRunning file is a much better solution than what
we have now.

**Comment by chrisgorgo** [comment]
Closed via #10
