### ISSUE TITLE
python dependency conflicts when trying to build the latest image

### ISSUE THREAD

**Issue by Remi-Gau** [BIDS-Apps/freesurfer#70]
https://app.circleci.com/pipelines/github/bids-apps/freesurfer/48/workflows/013143a5-bb0b-4312-bbfe-fe312822a81d/jobs/271

[log.txt](https://github.com/bids-apps/freesurfer/files/10340599/log.txt)

**Comment by Shotgunosine** [comment]
I think this is resolved by #67

**Comment by Remi-Gau** [comment]
yup!!
